CREATE TABLE contract_tbl (
  ID int NOT NULL AUTO_INCREMENT,
  name varchar(100) NOT NULL,
  consumer varchar(45) DEFAULT NULL,
  provider varchar(45) DEFAULT NULL,
  content varchar(255) DEFAULT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;